namespace ExceptionDemo
{

    public class Program
    {

        public static void Main()
        {


            //BasicException.ExceptionD();

            FinallyException.FinallyDemo();

            //try
            //{
            //    Console.WriteLine("Inside Main");
            //    var tdemo = new ThrowCatch();
            //    tdemo.Method2();
            //}
            //catch(Exception ex)
            //{
            //    Console.WriteLine("Insdide main catch ");
            //    throw;

            //}

           



        }
    }
}